In [ ]:
# 데이터 인코딩
# 1. 레이블 인코딩: 카테고리형 문자열을 숫자로 변환
from sklearn.preprocessing import LabelEncoder

# 변환할 카테고리형(값이 정해져 있다.) 문자열
# 값이 정해져 있다. ['TV','냉장고','전자레인지','컴퓨터','선풍기','믹서'] 6개

# 데이터 :[0 1 4 5 3 3 2 2]
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']


# LabelEncoder를 객체로 생성한 후 , fit( ) 과 transform( ) 으로 label 인코딩 수행.
encoder = LabelEncoder()
# fit : 카테고리를 알파벳, 가나다 순으로 정렬해야 함.
encoder.fit(items)  # 정렬 후 단어별 인덱스값 
labels = encoder.transform(items)   # 숫자로 변환.
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [3]:
print("인코딩 클래스:", encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [6]:
# 디코딩: 숫자 -> 문자열
print('디코딩 원본 값:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [ ]:
# 레이블 인코딩 문제점: 크기가 틀림. 레이블 인코딩에서 숫자는 큰 의미 없음. 
#                     그런데 머신러닝, 딥러닝에서는 값의 차이도 학습 대상.
#                     값의 크기를 같게 해줘야 함 : 원-핫 인코딩(행렬변환)
# 원-핫 인코딩: 문자열 => 숫자 변환



In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np


items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']


# 2차원 ndarray로 변환합니다.[["TV"],["냉장고"], ... ]
items = np.array(items).reshape(-1, 1)


# 원-핫 인코딩을 적용합니다.
oh_encoder = OneHotEncoder()

# 고유값 찾아 컬럼 구성(items에서 중복값 지운 후 컬럼 구성) ['TV','냉장고','믹서','선풍기','전자레인지','컴퓨터']
                                            # TV를 인코딩  1      0      0      0          0         0 
                                         # 냉장고를 인코딩  0      1      0      0          0         0 
oh_encoder.fit(items)   # fit(MetrixLike) Metrix(행렬) : 2차원. so items를 2차원으로 변환.

oh_labels = oh_encoder.transform(items) # transform : 변환


# OneHotEncoder로 변환한 결과는 희소행렬이므로 toarray()를 이용해 밀집 행렬로 변환.
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

# 값은 1이 최대이니 크기 차이가 나지 않음.(레이블 인코딩은 숫자가 커짐.)


원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [8]:
import pandas as pd


df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
pd.get_dummies(df)


,item_TV,item_냉장고,item_믹서,item_선풍기,item_전자레인지,item_컴퓨터
0,True,False,False,False,False,False
1,False,True,False,False,False,False
2,False,False,False,False,True,False
3,False,False,False,False,False,True
4,False,False,False,True,False,False
5,False,False,False,True,False,False
6,False,False,True,False,False,False
7,False,False,True,False,False,False


In [9]:
# 피처 스케일링과 정규화
# 데이터의 크기와 범위 틀린 문제 때문에 => 성능 떨어지는 문제 발생
# 데이터의 크기, 범위를 일정하게 만들어 줘야 함. : 피처 스케일링, 정규화
# 머신러닝은 1km 와 1000m 중 1000m를 더 크게 느낌. => 범위를 같게 처리.

In [ ]:
# StandardScaler(표준화)
# 붓꽃 데이터의 컬럼별 범위(평균, 분산) 구하기
# 평균: 중심점, 분산: 중심으로부터 퍼져있는 정도.
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환합니다.
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)


print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())
# 분산이 너무 크면 특징이 없다.(너무 범위가 넓음.) 예. patal length(0.6.. ~ 6.8)

# 모든 값의 평균을 (0,0)으로 몰기
# 값을 표준편차(분산)(자기 크기)만큼 나누면 크기는 1이 됨.

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [11]:
from sklearn.preprocessing import StandardScaler


# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)


#transform( )시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())


feature 들의 평균 값
sepal length (cm)   -4.736952e-16
sepal width (cm)    -7.815970e-16
petal length (cm)   -4.263256e-16
petal width (cm)    -4.736952e-16
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64
