In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])  # ndarray 생성
print('array1 type:',type(array1))  # ndarray object
print('array1 array 형태:',array1.shape)    # shape: 배열 형태가 튜플로 나옴(3,)


array2 = np.array([[1,2,3],     # ndarray 생성
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)    #(2,3)


array3 = np.array([[1,2,3]])        # 2차원 배열(값이 하나라도)
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
# ndim: 배열의 차원 확인
print(f"array1 : {array1.ndim}차원, array2 : {array2.ndim}차원, array3 : {array3.ndim}차원")

array1 : 1차원, array2 : 2차원, array3 : 2차원


In [4]:
list1 = [1,2,3]   
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
list2 = [1, 2, 'test']      # 하나 str이면 다 str로 바뀜(U21은 유니코드)
array2 = np.array(list2)
print(array2, array2.dtype)


list3 = [1, 2, 3.0]         # 하나 float면 다 float로 바뀜.    
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
# 숫자 1억건 배열. 0~5 사이의 값 저장. int64 타입이면 거의 61비트 낭비
# astype()써서 int8로 변환하면 메모리 절약 & 속도 더 빠르게.

In [7]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)


array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)


array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int8')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int8


In [8]:
# ndarray 생성하는 메소드 : array(), arange(), zeros(), ones()
# arange()는 range()와 같음. 다른 점은 range는 return list, arange는 return ndarray

In [9]:
# ndarray 생성 : array(), arange(), zeros(), ones()
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)


one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
array1 = np.arange(10)
print('array1:\n', array1)


array2 = array1.reshape(2,5)
print('array2:\n',array2)


array3 = array1.reshape(5,2)
print('array3:\n',array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1 = np.arange(10)
print(array1)


array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)


array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

# array4 = array1.reshape(-1,4)   # 나누어 떨어져야 함.


[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())


# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)


# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [13]:
# 1에서 부터 9 까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)    # (9,)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]       # 단일값 : 인덱싱
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [14]:
print('array1:',array1)
array1[0] = 9
array1[8] = 0       # 대입도 가능.
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]
array1: [9 2 3 4 5 6 7 8 0]


In [15]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)


print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


In [16]:
# 1차원 슬라이싱
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array1)
print(array3)
print(type(array3)) # ndarray에서 슬라이싱해도 ndarray 타입.


[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [17]:
array1 = np.arange(start=1, stop=10)
print(array1)


array4 = array1[:3]
print(array4)


array5 = array1[3:]
print(array5)

# arr = array1  복사 안 됨.(주소값 대입)
array6 = array1[:]  # 복사
print(array6)


[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [18]:
# 2차원 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)


print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])    # 복사
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [19]:
print(array2d)
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [20]:
# 팬시색인 : 비연속 
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d \n',array2d)


array3 = array2d[[0,2], 2]      # 팬시 색인할 때 리스트로 씀.
print('array2d[[0,2], 2] => ',array3.tolist())


array4 = array2d[[0,2], 0:2]
print('array2d[[0,2], 0:2] => ',array4.tolist())


array5 = array2d[[0,2]]
print('array2d[[0,2]] => ',array5.tolist())

print(f"array2d[[0,2],[0,2]] : \n{array2d[[0,2],[0,2]]}")

array2d 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,2], 2] =>  [3, 9]
array2d[[0,2], 0:2] =>  [[1, 2], [7, 8]]
array2d[[0,2]] =>  [[1, 2, 3], [7, 8, 9]]
array2d[[0,2],[0,2]] : 
[1 9]


In [21]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
# array1d 에서 특정 index 값으로 추출
# indexes = np.array([5,6,7,8])
arr4 = array1d[[5,6,7,8]]   # 엄밀히 말하면 팬시색인.[[인덱스]]
print(arr4)

[6 7 8 9]


In [ ]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort( )로 정렬
sort_array1 = np.sort(org_array)    # ascending 밖에 못함.(메소드 보니까 asc 설정이 없음.) 내림차순 불가
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()  # 반환되는 값이 없음.  # ascending 밖에 못함.(메소드 보니까 asc 설정이 없음.) 내림차순 불가
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
# 내림차순(descending) : sort 한 다음, 슬라이싱으로 처리하면 내림차순 가능
org_array = np.array([3,1,9,5])
sort_arr1 = np.sort(org_array)
print(f'원본 데이터 : {org_array}') # 원본 유지된다.
print(f'정렬한 데이터 : {sort_arr1}')   # 전체 데이터
print(f'정렬한 데이터 : {sort_arr1[:]}')    # 슬라이싱 전체 데이터
print(f'정렬한 데이터 내림차순 : {sort_arr1[::-1]}')    # 슬라이싱한 상태에서 step : -1 거꾸로 가져옴.


원본 데이터 : [3 1 9 5]
정렬한 데이터 : [1 3 5 9]
정렬한 데이터 : [1 3 5 9]
정렬한 데이터 내림차순 : [9 5 3 1]


In [ ]:
# 2차원 데이터 정렬
# 2차원(행, 열) 축 존재

array2d = np.array([[8, 12],
                   [7, 1 ]])


sort_array2d_axis0 = np.sort(array2d, axis=0)      # axis=0 : 행 방향
print('로우 방향으로 정렬:\n', sort_array2d_axis0)  # 행 방향(위에서 아래 방향)으로 정렬. (7 vs 8), (12 vs 1)


sort_array2d_axis1 = np.sort(array2d, axis=1)      # axis=1 : 열 방향
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)  # 열 방향(좌에서 우 방향)으로 정렬. (8 vs 12), (7 vs 1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [ ]:
# 정렬? : 크기 비교, 오름차순한 다음 첫번째 값(min), 내림차순한 다음 첫번째 값(max)
# 정렬된 인덱스 반환 함수 : np.argsort(정렬할 data)
# 정렬한 다음 인덱스만 추출할 수 있음.
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)    # argsort: 정렬된 배열의 인덱스 추출.
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)
# 1: 가장 작은 수, 2: 가장 큰 수.(인덱스로 서열에 따른 숫자 파악 가능)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1] # 내림차순 핵심.
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)


행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
# argsort 예제
# 점수에 의해 정렬된 이름을 구한다.
import numpy as np


score_array= np.array([78, 95, 84, 98, 88])
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])  # 가장 높은 점수의 인덱스 가져오기


sort_indices_asc = np.argsort(score_array)[::-1]    # 현재 내림차순.
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])



성적 오름차순 정렬 시 score_array의 인덱스: [3 1 4 2 0]
성적 오름차순으로 name_array의 이름 출력: ['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


In [39]:
# 내적: np.dot(), @
# 데이터 
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])


dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [41]:
# 전치 행렬
A = np.array([[1, 2, 5],
              [3, 4, 6]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)


A의 전치 행렬:
 [[1 3]
 [2 4]
 [5 6]]
