In [2]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])  # ndarray 생성
print('array1 type:',type(array1))  # ndarray object
print('array1 array 형태:',array1.shape)    # shape: 배열 형태가 튜플로 나옴(3,)


array2 = np.array([[1,2,3],     # ndarray 생성
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)    #(2,3)


array3 = np.array([[1,2,3]])        # 2차원 배열(값이 하나라도)
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
# ndim: 배열의 차원 확인
print(f"array1 : {array1.ndim}차원, array2 : {array2.ndim}차원, array3 : {array3.ndim}차원")

array1 : 1차원, array2 : 2차원, array3 : 2차원


In [ ]:
list1 = [1,2,3]   
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1, 2, 'test']      # 하나 str이면 다 str로 바뀜(U21은 유니코드)
array2 = np.array(list2)
print(array2, array2.dtype)


list3 = [1, 2, 3.0]         # 하나 float면 다 float로 바뀜.    
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
# 숫자 1억건 배열. 0~5 사이의 값 저장. int64 타입이면 거의 61비트 낭비
# astype()써서 int8로 변환하면 메모리 절약 & 속도 더 빠르게.

In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)


array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)


array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int8')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[127   2   3] int8


In [ ]:
# ndarray 생성하는 메소드 : array(), arange(), zeros(), ones()
# arange()는 range()와 같음. 다른 점은 range는 return list, arange는 return ndarray

In [ ]:
# ndarray 생성 : array(), arange(), zeros(), ones()
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)


one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [23]:
array1 = np.arange(10)
print('array1:\n', array1)


array2 = array1.reshape(2,5)
print('array2:\n',array2)


array3 = array1.reshape(5,2)
print('array3:\n',array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
array1 = np.arange(10)
print(array1)


array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)


array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

# array4 = array1.reshape(-1,4)   # 나누어 떨어져야 함.


[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [5]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())


# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)


# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [6]:
# 1에서 부터 9 까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)    # (9,)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]       # 단일값 : 인덱싱
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [7]:
print('array1:',array1)
array1[0] = 9
array1[8] = 0       # 대입도 가능.
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]
array1: [9 2 3 4 5 6 7 8 0]


In [8]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)


print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


In [ ]:
# 1차원 슬라이싱
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array1)
print(array3)
print(type(array3)) # ndarray에서 슬라이싱해도 ndarray 타입.


In [13]:
array1 = np.arange(start=1, stop=10)
print(array1)


array4 = array1[:3]
print(array4)


array5 = array1[3:]
print(array5)

# arr = array1  복사 안 됨.(주소값 대입)
array6 = array1[:]  # 복사
print(array6)


[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [14]:
# 2차원 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)


print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])    # 복사
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [15]:
print(array2d)
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [ ]:
# 팬시색인 : 비연속 
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d \n',array2d)


array3 = array2d[[0,2], 2]      # 팬시 색인할 때 리스트로 씀.
print('array2d[[0,2], 2] => ',array3.tolist())


array4 = array2d[[0,2], 0:2]
print('array2d[[0,2], 0:2] => ',array4.tolist())


array5 = array2d[[0,2]]
print('array2d[[0,2]] => ',array5.tolist())

print(f"array2d[[0,2],[0,2]] : \n{array2d[[0,2],[0,2]]}")

array2d 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,2], 2] =>  [3, 9]
array2d[[0,2], 0:2] =>  [[1, 2], [7, 8]]
array2d[[0,2]] =>  [[1, 2, 3], [7, 8, 9]]
array2d[[0,2],[0,2]] : 
[1 9]
